### ISSUE TITLE
Filtered between selector

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#1]
The following selector `[mousedown[!event.item], window:mouseup] > window:mousemove` throws an error `spec.html:92 Empty between selector: [mousedown[!event.item], window:mouseup] > window:mousemove`.

**Comment by arvind** [comment]
`[(mousedown[!event.item]), window:mouseup] > window:mousemove` does the same as well.

**Comment by jheer** [comment]
Added in f8886333219f07bf9f0ff3160c8e41d7671d9d69.
