### ISSUE TITLE
vlSelection functions not called on dataset update

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#13]
If either of the `vlSelection` functions are used by themselves in a production rule test function, they are not called when the referenced dataset changes. I believe this is because we do not have a `vlSelectionVisitor` to add a parameter reference to the dataset?

We missed this earlier because our test specs always used a `tuples` call (in addition to the `vlSelection`) which wired up the nodes correctly. However, the `tuples` call should no longer be necessary since `vlSelection` returns `true` if the dataset is empty.

**Comment by jheer** [comment]
Fixed in 8d421275b1eec3bd90c23332ab7bdacb608d0ff4.
