### ISSUE TITLE
Why -Default suffix for axis config's domain/grid/label/tick?

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#15]
I guess everything in config supposes to be default value anyway.
Why only these four get `-Default` suffix?

At first I was thinking if you try to avoid direct matching to actual Axis definition's property names.
However, legend config also has `orient`, `offset`, `padding` properties without `-Default` suffix.

**Comment by jheer** [comment]
I thought it was slightly clearer to add that suffix, as my thinking was something like "should tick/label/grid/domain be included by default"? But I see your point about matching the spec properties. I don't have a very strong opinion here, and would be happy to make the change if others agree. @domoritz? @arvind?

**Comment by jheer** [comment]
This was changed to be consistent in 59ca8f216e99003a8f37fe1b842a9ee85d73b845. `tickDefault` is now simply `tick` (for example).
