### ISSUE TITLE
Should `rangeStep: <number>` become `range: {step: <number>}`?

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#16]
Before the recent changes, there are three properties that can affect scale's range  (`range`, `rangeStep`, `scheme`).  

Now that `scheme` becomes a part of `range`.  I wonder if we should just collapse `rangeStep: <number>` to become `range: {step: <number>}` so everything falls under `range`?

(I don't have a strong opinion here -- just asking!)

**Comment by jheer** [comment]
Thanks! Yes, this could be a cleaner design, less error-prone, design. I'll look into it.

**Comment by jheer** [comment]
Fixed in 04b5a3b6fbb1e67cd865877175a93971d22cc5f6. Will be included in Vega v3.0.0-beta.16.
