### ISSUE TITLE
Skip non-mark properties when reading non-mark config.

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#23]
With the current implementation of Vega Mark Config, any config value inside a Vega mark config or role config will be included the scene graph.

However, some mark configs that are specific to Vega-Lite (e.g. `config.mark.color`, `config.<role>.color`) will currently pollute the scenegraph (https://github.com/vega/vega-lite/issues/1995). 

We discussed renaming these configs earlier; however, I don't think there is really a better place for these configs to reside.  (For example, `config.markColor/barColor` or `config.vl.markColor/barColor` would be non-intuitive for Vega-Lite users as compared to `config.mark/bar.color`.) 

Thus, I wonder if it is possible to have vega-parser's encode-util [skip](https://github.com/vega/vega-parser/blob/master/src/parsers/encode/encode-util.js#L50) non-mark properties.

From reading the code, it seems like we could add another line for the `skip` variable to check if the key is a member of the `encodeEntry` schema defined in the [schema generation code](https://github.com/vega/vega-parser/blob/master/schema/encode.js#L224).

I can see that one drawback of this approach is that `src/` will depend on a part of `schema/` but maybe that's not a bad thing.  For a reference point, TS code does import schema in their source all the time, so I think this isn't entirely unclean.

**Comment by jheer** [comment]
Unfortunately this is not an easy request to support. The Vega parser and runtime do not use a fixed schema of mark encoding properties: they are extensible by default, and the fact that these values get written to the scenegraph is a feature, not a bug. So I don't see how we can reasonably skip properties as you suggest.

While it is true that the schema currently restricts the properties for Vega JSON specs, we actually make use of non-standard properties internally (for example when generating axes and legend spec in vega-parser). Of course, this is a separate issue.
