### ISSUE TITLE
Add titleAngle config?

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#28]
I'm redirecting a request in https://github.com/vega/vega-lite/issues/2333.  

If we think we should do it, we should support it in Vega Config.

**Comment by jheer** [comment]
It should already be supported. By default the angle is dependent on the orientation, and hence omitted from the default config file. However, you should be able to add `axis.titleAngle` to the config to set it to a constant value.

It is already documented at [https://vega.github.io/vega/docs/config/](https://vega.github.io/vega/docs/config/). For the implementation, see [https://github.com/vega/vega-parser/blob/master/src/parsers/guides/axis-title.js#L49](https://github.com/vega/vega-parser/blob/master/src/parsers/guides/axis-title.js#L49).

If this is not working, then we have a bug. In that case, go ahead and file a new issue!

**Comment by kanitw** [comment]
Oh I See. 

Since the list of config in README.md in this repo is outdated, I wonder if we should just remove them and point to https://vega.github.io/vega/docs/config/ instead?
