### ISSUE TITLE
`debug` expression operator

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#3]
I'd like to be able to debug what an object looks like in a vega expression. 

Let's say I'm trying to write an expression for a formula transform. I want to know what properties the `datum` has and what their types are. 

```js
{
  "type": "formula",
  "as": "height",
  "expr": "(datum[\"???\"] + 1) * 21"
}
```

Maybe I can write something like

```js
{
  "type": "formula",
  "as": "height",
  "expr": "debug(datum)"
}
```

and would either get a JSON representation of the object or the object gets logged in the console (or both so I can see for example objects in axis labels).

**Comment by jheer** [comment]
I imagine this being a pure "side-effect" method. The return value would be identical to the input value, but internally a debug message would be generated using the existing dataflow/view logger instance. Sound good?

By default, I think one would need to have the debug logging level set (e.g., vega.Debug) for messages to actually be generated and printed. Among other things, this would allow debug messages to be optionally included but "turned off" to improve performance and squash output. The drawback is that some folks might be confused when their debug calls have no apparent effect (likely to happen since the default logging level is for Warn messages only). Please respond with any opinions on this question...

**Comment by kanitw** [comment]
Another related question:

Since the goal is not to derive a new field, I'm wondering why it should be an expression in a formula transform rather than its own "debug" transform or something similar?

**Comment by jheer** [comment]
Sorry @kanitw, I don't think I understand your question. For general operators, simply calling `view.logLevel(vega.Debug)` will result in rich console debugging output, including inspectable state for all operators and pulses that execute. So I'm not sure what a `Debug` transform would add to this.

OTOH, I can totally appreciate the need for a `debug` method in the expression language. There are plenty of times I personally would have found it useful. My suggestion above is also flexible (e.g., one could call debug in multiple places within the same expression, no problem). The `debug` method probably needs to accept at least two parameters: the value to log, and an optional additional message to include to help disambiguate multiple debug outputs.

For me, the main open question is what the appropriate log-level should be for this. The `vega.Debug` level seems the most obvious, but might be missed by some users and could also lead to expression debug messages getting drowned out among all the Operator-level debug outputs. So I'm trying to determine if either `Warn` or `Info` are more sensible default logging levels for expression debug statements. One could argue that if one explicitly invokes debug, one wants to see the message by default, and one could always use log level `None` to suppress all output.

**Comment by arvind** [comment]
Couple of alternatives I see:

* Separate functions for the each level, which would only log the message
if the threshold is met.
* A property within the config block to control log level; has the added
benefit of only logging output from one Vega visualization on a page that
contains several.

**Comment by domoritz** [comment]
The debug function could take the log level as another optional log level parameter that defaults to `Info`, `Debug` or `Warn`. I guess this is similar to @arvind's suggestion to have separate `debug`, `info`, and `warn` methods. 

I think a log level of `Debug` is too low because there are many other messages being logged and it'd be hard to find the one about the expression. I probably want to always see the output and once I'm done writing my expression, I would remove the debug statement.

**Comment by jheer** [comment]
I like @arvind's suggestion and have added `debug`, `info` and `warn` functions in 045abbcb728f3415ae34600459ed12a9528daf0a. This provides the most flexibility for both debugging and logging. Thanks!

**Comment by domoritz** [comment]
I just used `warn` and immediately found out what the right property name is. :-D
