### ISSUE TITLE
Allow "deactivating" certain expression functions

### ISSUE THREAD

**Issue by rgrochowicz** [uwdata/vega-parser#31]
Specifically, there's a need not to allow the `open` function during a `filter` expression.

**Comment by jheer** [comment]
If added, "deactivation" would happen via the JavaScript API, not through any spec-level directives. I assume that is OK?

Or, now that Vega 3 supports an `href` attribute that lets marks serve as hyperlinks, I wonder if the `open` command is really needed anymore. It might be nice to reduce both surface area and security vulnerabilities. If anyone has major objections to dropping `open` from the eventual 3.0 release, please let it be known. One could always add an "open" functionality in the JS environment via a signal listener or by explicitly registering it as a new (externally defined) expression function.

**Comment by jheer** [comment]
For the reasons described above, I've removed the `open` function from the standard expression set in 34cd3a9a496255f66896e905d6e4bab5bfc2bd77. If someone wants similar functionality, they can always add it (either via listeners or by registering a function with the `vega.expressionFunction` method).

Also, if you'd like to remove a function you can do it by overwriting an existing function. Use the `vega.expressionFunction` to register a new function with an existing name (e.g., your new function might simply raise an error) to effectively "remove" the pre-existing function.
