### ISSUE TITLE
Duplicate signal names when push: outer

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#37]
I would expect the following top-level spec to be illegal but `"push": "outer"` with the second signal seems to make this allowable? 

```json
{
  "signals": [
    {"name": "foo"},
    {"name": "foo", "push": "outer"}
  ]
}
```

**Comment by jheer** [comment]
It's legal and should work as expected. It is certainly unnecessary and gratuitous, but not erroneous. We could either leave as-is or update the parser with logic that throws an error. The other tricky bit is the JSON schema; can we easily make this invalid with JSON schema constructs? As a result I lean toward leaving this as-is...

**Comment by arvind** [comment]
I'm fine leaving it as is. Just wanted to call it out in case it was supposed to be errroneous. Thanks!
