### ISSUE TITLE
Better error log for missing transform parameter

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#4]
Currently [this line](https://github.com/vega/vega-parser/blob/master/src/parsers/transform.js#L46) output 
```
'Missing required parameter: ' + def.name
```
if a transform miss a required parameter. 

However, it might be hard for users to know which transform the error log is talking about. 

One minimal thing to add would be the type of the transform that's missing the parameter.

**Comment by jheer** [comment]
Added in fe134ae1a4d0c1bd41e7e1f67679de142c2e7706.
