### ISSUE TITLE
Filter + consume event selector

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#45]
`wheel[event.shiftKey]!` throws the error `Uncaught Expected left bracket: wheel[event.shiftKey]!` when I would expect it to produce:

```json
{
  "type": "wheel",
  "consume": true,
  "filter": ["event.shiftKey"]
}
```

**Comment by jheer** [comment]
I think this is a bug in [vega/vega-event-selector](https://github.com/vega/vega-event-selector), not vega-parser?

**Comment by jheer** [comment]
In any case, it looks like the error concerns the inclusion of `!` at the end. Will look to improve the logic soon but have a packed schedule today. PRs welcome if you produce a fix in the meantime.

**Comment by jheer** [comment]
Wait a second: I think your selector is wrong. I think it should be `wheel!`, then followed by filters.

**Comment by arvind** [comment]
:man_facepalming:
