### ISSUE TITLE
Default legend symbolColor always applied to stroke even when fill is specified

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#46]
Vega legend has symbol color as gray 

```
symbolColor: gray,
```

Currently this is applied even when `fill` is specified, which seems a bit magical. 
(FWIW, @domoritz  thought this was a bug in https://github.com/vega/vega-lite/issues/2626.) 

(See compiled output of the Vega-Lite's Github Punchcard example: https://vega.github.io/editor/#/examples/vega-lite/github_punchcard)

We could make Vega-Lite output `stroke: {value: null}` but before we do that, we wanna make sure if this behavior is intended in Vega.

**Comment by jheer** [comment]
Thanks! That looks like a bug in [legend-symbols.js#L17](https://github.com/vega/vega-parser/blob/master/src/parsers/guides/legend-symbols.js#L17). Will fix soon!

**Comment by jheer** [comment]
Fixed in a572fa841111207358da2917102e350ce4755d8e. Released in v1.1.2.
