### ISSUE TITLE
Swap order of logging expr function arguments?

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#6]
The newly introduced `info`, `warn` and `debug` expr functions all have a signature `(value, message)`. However, when logged to the console, this order is swapped (e.g., `WARN EXPRESSION message value`). It's unclear why the order is swapped and, when doing some quick and dirty expression logging, has already broken my brain a few times.

Ideally, these functions would mimic the native `console` methods and accept a variable number of arguments, and print them in the order they were passed.

**Comment by jheer** [comment]
This was to ensure the first value is always the return value. This could be swapped of course, with a little extra logic. Will put this on the queue, but beware of broken specs if we make this change.

**Comment by jheer** [comment]
Addressed by 53a32e2.
