### ISSUE TITLE
config.legend.labelAlign/Baseline exist but config.axis.labelAlign/Baseline are not listed in the docs

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-parser#62]
`config.legend.labelAlign/Baseline` exist but `config.axis.labelAlign/Baseline` are not listed in the [docs](https://vega.github.io/vega/docs/config/#axes)

~~I haven't checked if those properties exist in the code, but at least it is inconsistent in the docs, not sure if this is intended.~~  (Trying it in the editor doesn't work.)

**Comment by jheer** [comment]
This is not an error. Legends support arbitrary label alignment and baseline. Axes do not: the default alignment and baseline is determined based on the axis orientation and (as of v2.2.0) `labelFlush` settings.
