### ISSUE TITLE
Vega Typings

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#63]
It would be awesome to get https://github.com/vega/vega-parser/tree/as/typings in. We are currently copying some version of the Vega typings in Vega-Lite, Embed, and others.

**Comment by jheer** [comment]
Flagging @arvind...

**Comment by domoritz** [comment]
This came to bite us again in https://github.com/jupyterlab/jupyter-renderers/pull/15. In the last case, it was missing typings for vega-util. 

A big problem is that there are vega typings that are outdated at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/vega/index.d.ts. I think it's worth putting in the effort so that others don't get compile errors anymore.

**Comment by domoritz** [comment]
There are experimental typings at https://github.com/vega/vega-parser/tree/as/typings. We also now have typings for vega-util.

**Comment by domoritz** [comment]
Vega-Lite has its own version of Vega typings at https://github.com/vega/vega-lite/blob/master/src/vega.schema.ts.

**Comment by pelotom** [comment]
Would really love to have this. Currently I'm using `vega-lite` just to get access to `vega`'s typings.

**Comment by domoritz** [comment]
https://github.com/vega/vega/issues/1165

**Comment by pelotom** [comment]
FYI, I opened a PR to update the DefinitelyTyped typings based on the `vega-parser` typings branch and `vega-lite`'s typings for the vega runtime: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23808

**Comment by domoritz** [comment]
I moved the typings over to https://github.com/vega/vega-typings. It still needs some work, though.

**Comment by jheer** [comment]
Closing this issue as vega-typings now exists and is exported by Vega.
