### ISSUE TITLE
fontWeight should allow numbers

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#70]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/23808#discussion_r169737635. The schema currently only allows strings.

**Comment by jheer** [comment]
FWIW, this is not an oversight. The schema and docs type `fontWeight` as a string intentionally. The parameter does not accept arbitrary numbers, nor should it. CSS allows specific numbers: 100, 200, up to 900. (See https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight) Perhaps this could be an enum instead?

**Comment by domoritz** [comment]
It also doesn’t accept arbitrary strings, though.

JSON Schema supports min, max, and multiple of but also enums. Both are more accurate than only allowing strings.

**Comment by jheer** [comment]
See my last comment above :)

**Comment by jheer** [comment]
Fixed in vega-parser@2.6.0 onwards. We now use an enum for all legal values of fontWeight, including both strings and numbers.
