### ISSUE TITLE
Projection property fit can be an object but parser throws an error

### ISSUE THREAD

**Issue by manuelroth** [uwdata/vega-parser#71]
Hi everyone,
This is an awesome project. Thank you so much for putting so many thoughts into this. I am just getting started, but love how well the project is documented and that you provide an editor to play around with it.

**Issue**
I want to use the `fit` projection property documented [here](https://vega.github.io/vega/docs/projections/). The documentation says that it can be either a GeoJSON Feature/FeatureCollection object or an array. 
I found out that the [parser](https://github.com/vega/vega-parser/blob/master/src/parsers/projection.js#L16) doesn't allow any property to be of type object and throws an [`Unsupported parameter`](https://github.com/vega/vega-parser/blob/master/src/parsers/projection.js#L18) error when I am setting the fit property to an object.

Here a link to a vega spec to reproduce the error: https://gist.github.com/manuelroth/962eb299e6d59b038779e7857cd64b3f

- Is the fit property not yet supported?- Or did I do something wrong?- I would love to use this feature, it would make my work so much easier. I would be happy to help fix this, if necessary.

**Comment by jheer** [comment]
Thanks @manuelroth!  Fixed and released in vega-parser@2.6.1, will be included in next Vega release.
