### ISSUE TITLE
Parameterized default source for event selector parser

### ISSUE THREAD

**Issue by arvind** [uwdata/vega-parser#8]
Vega-Lite users `vega-parser.selector` to parse event selectors in order to build out the necessary signals for a selection. By default, the source of events is set to `view` if no other valid source is specified. It would be helpful if this default was parameterized, such that Vega-Lite events could be sourced to `scope` by default. This seems simpler than having to traverse the JSON representation to replace `view` with `source` post-parse.

**Comment by jheer** [comment]
Added in 30e8669157332f61bf9f88836d51adee887b8f85.
