### ISSUE TITLE
Add `sort` or `extent`

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#81]
I'm looking for a way to make sure that a brush range is always sorted. The first element of the brush range should be less than the second. Right now, the easiest way seems to be to use `[min(first, second), max(brush(first, second))]` where `first` and `second` are some expressions. I'd like to just write `sort([first, second])`. 

* Input `[10, 20]`, output `[10,20]`
* Input `[20, 10]`, output `[10,20]`

**Comment by domoritz** [comment]
I guess an `extent` method that returns `[min(arr), max(arr)]` would work as well.

**Comment by jheer** [comment]
Added `extent` function in vega-parser v3.5.0.
