### ISSUE TITLE
What is `numberValue`?

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#82]
I would expect this to work but the schema expects an array. What is `numberValue`?

```
{
  "$schema": "https://vega.github.io/schema/vega/v4.json",
  "legends": [{
    "encode": {
      "symbols": {
        "enter": {
          "fill": {
           "color": {"r": 12, "g": 23, "b":2}
          }
        }
      }
    }
  }]
}
```

Shows a schema error `Incorrect type. Expected "array".`.

**Comment by jheer** [comment]
Number value is an encoding definition object that should ultimately evaluate to a number. In your example the RGB values should be objects with the key “value”, just like any other encoder.
