### ISSUE TITLE
Symbol and gradient opacity missing from legend properties

### ISSUE THREAD

**Issue by domoritz** [uwdata/vega-parser#83]
It would be nice if the opacity of the gradient and the symbols was a legend property so that Vega-Lite can generate legend properties rather than having to construct an encode block.

**Comment by jheer** [comment]
If opacity was being driven by a scale would this property be ignored? If so I think this should be straightforward to add.

**Comment by kanitw** [comment]
> If opacity was being driven by a scale would this property be ignored

Sounds reasonable to me :)

**Comment by jheer** [comment]
Fixed in vega-parser 3.6.0.
