### ISSUE TITLE
Schema error?

### ISSUE THREAD

**Issue by waywardmonkeys** [uwdata/vega-parser#93]
In the `data.js` file for the schema generation, commit 7dbfff40033d0f60d22306fe49d2be879cbea88e did this:

```
                    "url": stringOrSignal,
                    "format": [
                      {"$ref": "#/defs/dataFormat"},
                      {"$ref": "#/refs/signal"}
                    ]
```

I don't think that's valid as the `"format"` shouldn't be an array here, but probably a `oneOf`.

This breaks using `quicktype` to generate code from the resulting JSON schema.

**Comment by domoritz** [comment]
Is this invalid according to the json schema definition?

**Comment by waywardmonkeys** [comment]
I believe so. At least one validator fails on it as well (https://www.jsonschemavalidator.net/).

**Comment by domoritz** [comment]
Hmm, I don't get any errors with https://raw.githubusercontent.com/vega/schema/master/vega/v4.3.0.json:

<img width="533" alt="screen shot 2018-11-09 at 15 51 45" src="https://user-images.githubusercontent.com/589034/48294147-65f9bd00-e437-11e8-8442-e23c39f046c4.png">

**Comment by waywardmonkeys** [comment]
I copied and pasted the v4.3.0 schema into the text field on the left and I get:

```
Unexpected token encountered when reading value for 'format'. Expected StartObject, got StartArray. Path 'defs.data.allOf[1].anyOf[1].oneOf[2].properties.format', line 990, position 31.
```

That corresponds to the error that I also get with `quicktype`.

**Comment by domoritz** [comment]
I put in in the right side and selected the draft 4 - 6 specs on the left but I guess that doesn't do the trick. I can see the error now. 

Anyway, the easiest fix is to just add `oneOf`. I submitted a PR in https://github.com/vega/vega-parser/pull/94.
